// Package depot_client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package depot_client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BundleStatus.
const (
	ATTACHED   BundleStatus = "ATTACHED"
	CANCELLED  BundleStatus = "CANCELLED"
	ERROR      BundleStatus = "ERROR"
	FAILED     BundleStatus = "FAILED"
	INPROGRESS BundleStatus = "IN_PROGRESS"
	INUSE      BundleStatus = "IN_USE"
	READY      BundleStatus = "READY"
)

// Valid indicates whether the value is a known member of the BundleStatus enum.
func (e BundleStatus) Valid() bool {
	switch e {
	case ATTACHED:
		return true
	case CANCELLED:
		return true
	case ERROR:
		return true
	case FAILED:
		return true
	case INPROGRESS:
		return true
	case INUSE:
		return true
	case READY:
		return true
	default:
		return false
	}
}

// Defines values for BundleType.
const (
	AVIOPERATIONS      BundleType = "AVI_OPERATIONS"
	AVIOPERATIONSPATCH BundleType = "AVI_OPERATIONS_PATCH"
	BMS                BundleType = "BMS"
	INSTALLER          BundleType = "INSTALLER"
	LICENSE            BundleType = "LICENSE"
	LICENSEPATCH       BundleType = "LICENSE_PATCH"
	PLATFORM           BundleType = "PLATFORM"
	PLATFORMPATCH      BundleType = "PLATFORM_PATCH"
	SVM                BundleType = "SVM"
)

// Valid indicates whether the value is a known member of the BundleType enum.
func (e BundleType) Valid() bool {
	switch e {
	case AVIOPERATIONS:
		return true
	case AVIOPERATIONSPATCH:
		return true
	case BMS:
		return true
	case INSTALLER:
		return true
	case LICENSE:
		return true
	case LICENSEPATCH:
		return true
	case PLATFORM:
		return true
	case PLATFORMPATCH:
		return true
	case SVM:
		return true
	default:
		return false
	}
}

// AddonBundle Information about an add-on bundle.
type AddonBundle struct {
	// BundleType Type of the bundle
	BundleType *BundleType `json:"bundle_type,omitempty"`

	// BundleVersion Version of the bundle.
	BundleVersion *string `json:"bundle_version,omitempty"`

	// Description Description of bundle contents.
	Description *string `json:"description,omitempty"`

	// Id ID of the bundle.
	Id *string `json:"id,omitempty"`

	// Required Whether the bundle is mandatory to consume.
	Required *bool `json:"required,omitempty"`
}

// AsyncApiResponse Response returned for asynchronous operations.
type AsyncApiResponse struct {
	// Id Workflow or job ID.
	Id *string `json:"id,omitempty"`

	// StatusUrl URL to poll for status.
	StatusUrl *string `json:"status_url,omitempty"`
}

// Bundle Information about a bundle.
type Bundle struct {
	// Addons List of add-on bundles.
	Addons []AddonBundle `json:"addons"`

	// BundleType Type of the bundle
	BundleType *BundleType `json:"bundle_type,omitempty"`

	// BundleVersion Version of the bundle
	BundleVersion *string `json:"bundle_version,omitempty"`

	// CreatedAt Resource creation time.
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Id Unique identifier for the resource.
	Id *string `json:"id,omitempty"`

	// Message Message related to the bundle upload
	Message *string `json:"message,omitempty"`

	// PackagedTime Milliseconds since Unix epoch.
	PackagedTime EpochMsTimestamp `json:"packaged_time"`

	// ParentId For patch bundles, the id of the base bundle
	ParentId *string `json:"parent_id,omitempty"`

	// Progress Bundle upload progress in percentage, 0-100
	Progress *int `json:"progress,omitempty"`

	// Size Size of the bundle in bytes
	Size *int `json:"size,omitempty"`

	// Status Status of the bundle
	Status *BundleStatus `json:"status,omitempty"`

	// UpdatedAt Resource last update time.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// BundleStatus Status of the bundle
type BundleStatus string

// BundleType Type of the bundle
type BundleType string

// EpochMsTimestamp Milliseconds since Unix epoch.
type EpochMsTimestamp = int64

// Error API error response format.
type Error struct {
	Details      *[]string `json:"details,omitempty"`
	ErrorCode    *int      `json:"error_code,omitempty"`
	ErrorMessage *string   `json:"error_message,omitempty"`
}

// ListBundles List of bundles
type ListBundles struct {
	Cursor      *string `json:"cursor,omitempty"`
	ResultCount *int    `json:"result_count,omitempty"`

	// Results List of SSPI bundles.
	Results *[]Bundle `json:"results,omitempty"`
}

// ListResult Base pagination fields.
type ListResult struct {
	Cursor      *string `json:"cursor,omitempty"`
	ResultCount *int    `json:"result_count,omitempty"`
}

// LocalUpload Provide the local bundle file for the depot to receive and store in the registry
type LocalUpload struct {
	// File Local bundle file.
	File openapi_types.File `json:"file"`
}

// ManagedResource Common fields for managed resources.
type ManagedResource struct {
	// CreatedAt Resource creation time.
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Id Unique identifier for the resource.
	Id *string `json:"id,omitempty"`

	// UpdatedAt Resource last update time.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// RemoteUpload Provide the remote bundle URL for the depot to download and store in the registry
//
// Example: {"url":"https://example.com/resources/bundle.tar"}
type RemoteUpload struct {
	// Url Remote bundle URL
	Url string `json:"url"`
}

// BundleTypeFilter Type of the bundle
type BundleTypeFilter = BundleType

// Offset defines model for Offset.
type Offset = int

// PageSize defines model for PageSize.
type PageSize = int

// SortAscending defines model for SortAscending.
type SortAscending = bool

// SortBy defines model for SortBy.
type SortBy = string

// GetBundlesParams defines parameters for GetBundles.
type GetBundlesParams struct {
	// Offset Number of items to skip before starting to collect the result set.
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// PageSize The numbers of items to return.
	PageSize *PageSize `form:"pageSize,omitempty" json:"pageSize,omitempty"`

	// SortAscending Sort the items by Ascending (true) or Descending (false).
	SortAscending *SortAscending `form:"sortAscending,omitempty" json:"sortAscending,omitempty"`

	// SortBy Sort the items by a specific field.
	SortBy *SortBy `form:"sortBy,omitempty" json:"sortBy,omitempty"`
}

// UploadLocalBundleParams defines parameters for UploadLocalBundle.
type UploadLocalBundleParams struct {
	// Type Parameter to filter the bundles by type
	Type *BundleTypeFilter `form:"type,omitempty" json:"type,omitempty"`
}

// UploadRemoteBundleParams defines parameters for UploadRemoteBundle.
type UploadRemoteBundleParams struct {
	// Type Parameter to filter the bundles by type
	Type *BundleTypeFilter `form:"type,omitempty" json:"type,omitempty"`
}

// UploadLocalBundleMultipartRequestBody defines body for UploadLocalBundle for multipart/form-data ContentType.
type UploadLocalBundleMultipartRequestBody = LocalUpload

// UploadRemoteBundleJSONRequestBody defines body for UploadRemoteBundle for application/json ContentType.
type UploadRemoteBundleJSONRequestBody = RemoteUpload

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetBundles Get a list of bundles
	//
	// Corresponds with GET /sspi/bundles (the `GetBundles` operationId).
	GetBundles(ctx context.Context, params *GetBundlesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadLocalBundleWithBody Upload a bundle by providing a local bundle file
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /sspi/bundles/local (the `UploadLocalBundle` operationId).
	UploadLocalBundleWithBody(ctx context.Context, params *UploadLocalBundleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadRemoteBundleWithBody Upload a bundle by providing a remote bundle URL
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /sspi/bundles/remote (the `UploadRemoteBundle` operationId).
	UploadRemoteBundleWithBody(ctx context.Context, params *UploadRemoteBundleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadRemoteBundle Upload a bundle by providing a remote bundle URL
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /sspi/bundles/remote (the `UploadRemoteBundle` operationId).
	UploadRemoteBundle(ctx context.Context, params *UploadRemoteBundleParams, body UploadRemoteBundleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteBundle Delete an uploaded bundle or cancel a bundle upload process by ID
	//
	// Corresponds with DELETE /sspi/bundles/{id} (the `DeleteBundle` operationId).
	DeleteBundle(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetBundle Get information of an uploaded bundle by ID
	//
	// Corresponds with GET /sspi/bundles/{id} (the `GetBundle` operationId).
	GetBundle(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDepotHealth Check depot health status
	//
	// Corresponds with GET /sspi/depot/health (the `GetDepotHealth` operationId).
	GetDepotHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetBundles Get a list of bundles
//
// Corresponds with GET /sspi/bundles (the `GetBundles` operationId).
func (c *Client) GetBundles(ctx context.Context, params *GetBundlesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBundlesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UploadLocalBundleWithBody Upload a bundle by providing a local bundle file
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /sspi/bundles/local (the `UploadLocalBundle` operationId).
func (c *Client) UploadLocalBundleWithBody(ctx context.Context, params *UploadLocalBundleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadLocalBundleRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UploadRemoteBundleWithBody Upload a bundle by providing a remote bundle URL
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /sspi/bundles/remote (the `UploadRemoteBundle` operationId).
func (c *Client) UploadRemoteBundleWithBody(ctx context.Context, params *UploadRemoteBundleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadRemoteBundleRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UploadRemoteBundle Upload a bundle by providing a remote bundle URL
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /sspi/bundles/remote (the `UploadRemoteBundle` operationId).
func (c *Client) UploadRemoteBundle(ctx context.Context, params *UploadRemoteBundleParams, body UploadRemoteBundleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadRemoteBundleRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteBundle Delete an uploaded bundle or cancel a bundle upload process by ID
//
// Corresponds with DELETE /sspi/bundles/{id} (the `DeleteBundle` operationId).
func (c *Client) DeleteBundle(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteBundleRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetBundle Get information of an uploaded bundle by ID
//
// Corresponds with GET /sspi/bundles/{id} (the `GetBundle` operationId).
func (c *Client) GetBundle(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBundleRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetDepotHealth Check depot health status
//
// Corresponds with GET /sspi/depot/health (the `GetDepotHealth` operationId).
func (c *Client) GetDepotHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDepotHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetBundlesRequest constructs an http.Request for the GetBundles method
func NewGetBundlesRequest(server string, params *GetBundlesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sspi/bundles")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "pageSize", *params.PageSize, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SortAscending != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sortAscending", *params.SortAscending, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SortBy != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sortBy", *params.SortBy, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUploadLocalBundleRequestWithBody constructs an http.Request for the UploadLocalBundle method, with any body, and a specified content type
func NewUploadLocalBundleRequestWithBody(server string, params *UploadLocalBundleParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sspi/bundles/local")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Type != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "type", *params.Type, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUploadRemoteBundleRequest calls the generic UploadRemoteBundle builder with application/json body
func NewUploadRemoteBundleRequest(server string, params *UploadRemoteBundleParams, body UploadRemoteBundleJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUploadRemoteBundleRequestWithBody(server, params, "application/json", bodyReader)
}

// NewUploadRemoteBundleRequestWithBody constructs an http.Request for the UploadRemoteBundle method, with any body, and a specified content type
func NewUploadRemoteBundleRequestWithBody(server string, params *UploadRemoteBundleParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sspi/bundles/remote")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Type != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "type", *params.Type, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteBundleRequest constructs an http.Request for the DeleteBundle method
func NewDeleteBundleRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sspi/bundles/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetBundleRequest constructs an http.Request for the GetBundle method
func NewGetBundleRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sspi/bundles/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDepotHealthRequest constructs an http.Request for the GetDepotHealth method
func NewGetDepotHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sspi/depot/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetBundlesWithResponse Get a list of bundles
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /sspi/bundles (the `GetBundles` operationId).
	GetBundlesWithResponse(ctx context.Context, params *GetBundlesParams, reqEditors ...RequestEditorFn) (*GetBundlesResponse, error)

	// UploadLocalBundleWithBodyWithResponse Upload a bundle by providing a local bundle file
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /sspi/bundles/local (the `UploadLocalBundle` operationId).
	UploadLocalBundleWithBodyWithResponse(ctx context.Context, params *UploadLocalBundleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadLocalBundleResponse, error)

	// UploadRemoteBundleWithBodyWithResponse Upload a bundle by providing a remote bundle URL
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /sspi/bundles/remote (the `UploadRemoteBundle` operationId).
	UploadRemoteBundleWithBodyWithResponse(ctx context.Context, params *UploadRemoteBundleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadRemoteBundleResponse, error)

	// UploadRemoteBundleWithResponse Upload a bundle by providing a remote bundle URL
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /sspi/bundles/remote (the `UploadRemoteBundle` operationId).
	UploadRemoteBundleWithResponse(ctx context.Context, params *UploadRemoteBundleParams, body UploadRemoteBundleJSONRequestBody, reqEditors ...RequestEditorFn) (*UploadRemoteBundleResponse, error)

	// DeleteBundleWithResponse Delete an uploaded bundle or cancel a bundle upload process by ID
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /sspi/bundles/{id} (the `DeleteBundle` operationId).
	DeleteBundleWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteBundleResponse, error)

	// GetBundleWithResponse Get information of an uploaded bundle by ID
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /sspi/bundles/{id} (the `GetBundle` operationId).
	GetBundleWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetBundleResponse, error)

	// GetDepotHealthWithResponse Check depot health status
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /sspi/depot/health (the `GetDepotHealth` operationId).
	GetDepotHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetDepotHealthResponse, error)
}

type GetBundlesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ListBundles
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetBundlesResponse) GetJSON200() *ListBundles {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r GetBundlesResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r GetBundlesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetBundlesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBundlesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetBundlesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UploadLocalBundleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON202 the response for an HTTP 202 `application/json` response
	JSON202 *AsyncApiResponse
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON202 returns the response for an HTTP 202 `application/json` response
func (r UploadLocalBundleResponse) GetJSON202() *AsyncApiResponse {
	return r.JSON202
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r UploadLocalBundleResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r UploadLocalBundleResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UploadLocalBundleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadLocalBundleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UploadLocalBundleResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UploadRemoteBundleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON202 the response for an HTTP 202 `application/json` response
	JSON202 *AsyncApiResponse
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON202 returns the response for an HTTP 202 `application/json` response
func (r UploadRemoteBundleResponse) GetJSON202() *AsyncApiResponse {
	return r.JSON202
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r UploadRemoteBundleResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r UploadRemoteBundleResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UploadRemoteBundleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadRemoteBundleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UploadRemoteBundleResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteBundleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r DeleteBundleResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r DeleteBundleResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteBundleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteBundleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteBundleResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetBundleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Bundle
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetBundleResponse) GetJSON200() *Bundle {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r GetBundleResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r GetBundleResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetBundleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBundleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetBundleResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetDepotHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r GetDepotHealthResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r GetDepotHealthResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetDepotHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDepotHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetDepotHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetBundlesWithResponse Get a list of bundles
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /sspi/bundles (the `GetBundles` operationId).
func (c *ClientWithResponses) GetBundlesWithResponse(ctx context.Context, params *GetBundlesParams, reqEditors ...RequestEditorFn) (*GetBundlesResponse, error) {
	rsp, err := c.GetBundles(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBundlesResponse(rsp)
}

// UploadLocalBundleWithBodyWithResponse Upload a bundle by providing a local bundle file
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /sspi/bundles/local (the `UploadLocalBundle` operationId).
func (c *ClientWithResponses) UploadLocalBundleWithBodyWithResponse(ctx context.Context, params *UploadLocalBundleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadLocalBundleResponse, error) {
	rsp, err := c.UploadLocalBundleWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadLocalBundleResponse(rsp)
}

// UploadRemoteBundleWithBodyWithResponse Upload a bundle by providing a remote bundle URL
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /sspi/bundles/remote (the `UploadRemoteBundle` operationId).
func (c *ClientWithResponses) UploadRemoteBundleWithBodyWithResponse(ctx context.Context, params *UploadRemoteBundleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadRemoteBundleResponse, error) {
	rsp, err := c.UploadRemoteBundleWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadRemoteBundleResponse(rsp)
}

// UploadRemoteBundleWithResponse Upload a bundle by providing a remote bundle URL
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /sspi/bundles/remote (the `UploadRemoteBundle` operationId).
func (c *ClientWithResponses) UploadRemoteBundleWithResponse(ctx context.Context, params *UploadRemoteBundleParams, body UploadRemoteBundleJSONRequestBody, reqEditors ...RequestEditorFn) (*UploadRemoteBundleResponse, error) {
	rsp, err := c.UploadRemoteBundle(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadRemoteBundleResponse(rsp)
}

// DeleteBundleWithResponse Delete an uploaded bundle or cancel a bundle upload process by ID
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /sspi/bundles/{id} (the `DeleteBundle` operationId).
func (c *ClientWithResponses) DeleteBundleWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteBundleResponse, error) {
	rsp, err := c.DeleteBundle(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteBundleResponse(rsp)
}

// GetBundleWithResponse Get information of an uploaded bundle by ID
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /sspi/bundles/{id} (the `GetBundle` operationId).
func (c *ClientWithResponses) GetBundleWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetBundleResponse, error) {
	rsp, err := c.GetBundle(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBundleResponse(rsp)
}

// GetDepotHealthWithResponse Check depot health status
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /sspi/depot/health (the `GetDepotHealth` operationId).
func (c *ClientWithResponses) GetDepotHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetDepotHealthResponse, error) {
	rsp, err := c.GetDepotHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDepotHealthResponse(rsp)
}

// ParseGetBundlesResponse parses an HTTP response from a GetBundlesWithResponse call
func ParseGetBundlesResponse(rsp *http.Response) (*GetBundlesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBundlesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListBundles
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseUploadLocalBundleResponse parses an HTTP response from a UploadLocalBundleWithResponse call
func ParseUploadLocalBundleResponse(rsp *http.Response) (*UploadLocalBundleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadLocalBundleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest AsyncApiResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseUploadRemoteBundleResponse parses an HTTP response from a UploadRemoteBundleWithResponse call
func ParseUploadRemoteBundleResponse(rsp *http.Response) (*UploadRemoteBundleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadRemoteBundleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest AsyncApiResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseDeleteBundleResponse parses an HTTP response from a DeleteBundleWithResponse call
func ParseDeleteBundleResponse(rsp *http.Response) (*DeleteBundleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteBundleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 200:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetBundleResponse parses an HTTP response from a GetBundleWithResponse call
func ParseGetBundleResponse(rsp *http.Response) (*GetBundleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBundleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Bundle
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetDepotHealthResponse parses an HTTP response from a GetDepotHealthWithResponse call
func ParseGetDepotHealthResponse(rsp *http.Response) (*GetDepotHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDepotHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
