// © Broadcom. All Rights Reserved.
// The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.

package provider

import (
	"context"
	"fmt"
	"net/url"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/vmware/terraform-provider-ssp/internal/provider/client"
)

var _ resource.Resource = &AlarmStateResource{}
var _ resource.ResourceWithImportState = &AlarmStateResource{}

func NewAlarmStateResource() resource.Resource {
	return &AlarmStateResource{}
}

// AlarmStateResource manages the acknowledgement/suppression of a pre-existing
// alarm instance by ID. Alarm instances are created by the platform, not by
// this resource — there is no POST/DELETE to create or remove one.
type AlarmStateResource struct {
	client *client.Client
}

type AlarmStateResourceModel struct {
	ID                types.String `tfsdk:"id"`
	DesiredState      types.String `tfsdk:"desired_state"`
	SuppressDuration  types.Int64  `tfsdk:"suppress_duration"`
	State             types.String `tfsdk:"state"`
	FeatureName       types.String `tfsdk:"feature_name"`
	Severity          types.String `tfsdk:"severity"`
	Summary           types.String `tfsdk:"summary"`
	Description       types.String `tfsdk:"description"`
	RecommendedAction types.String `tfsdk:"recommended_action"`
	ResourceID        types.String `tfsdk:"resource_id"`
	Value             types.String `tfsdk:"value"`
}

func (r *AlarmStateResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_alarm_state"
}

func (r *AlarmStateResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Acknowledges or suppresses a pre-existing alarm instance by ID.\n\n" +
			"Alarm instances are generated by the platform, not by this resource — there is no\n" +
			"`POST`/`DELETE` to create or remove one. Use `id` to adopt an existing instance\n" +
			"(see `data.ssp_alarms` to discover valid IDs).\n\n" +
			"`desired_state` accepts only the two real transition actions the API supports —\n" +
			"`ACKNOWLEDGE` or `SUPPRESS` — which is a narrower set than the `state` values an\n" +
			"alarm instance can report (`OPEN`, `ACKNOWLEDGED`, `SUPPRESSED`, `RESOLVED`); an\n" +
			"alarm transitions to `RESOLVED`/`OPEN` on its own once its underlying condition\n" +
			"changes, not via this API.\n\n" +
			"`Delete()` only removes this resource from Terraform state — there is no remote\n" +
			"call to undo an acknowledgement/suppression.\n\n" +
			"Corresponds to `POST /ssp/alarms/states` and `GET /ssp/alarms/{id}`.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "ID of the pre-existing alarm instance to acknowledge or suppress.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"desired_state": schema.StringAttribute{
				Required: true,
				MarkdownDescription: "Transition action to apply to the alarm instance. Real API enum " +
					"(`UpdatedState`): `ACKNOWLEDGE` or `SUPPRESS`.",
				Validators: []validator.String{stringvalidator.OneOf("ACKNOWLEDGE", "SUPPRESS")},
			},
			"suppress_duration": schema.Int64Attribute{
				Optional: true,
				MarkdownDescription: "Hours to suppress the alarm for, when `desired_state = \"SUPPRESS\"` " +
					"(0-12, defaults to 1 server-side if unset). Ignored for `ACKNOWLEDGE`.",
			},
			"state": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Actual current state of the alarm instance, as reported by the API.",
			},
			"feature_name": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Feature this alarm instance is associated with.",
			},
			"severity": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Severity level of this alarm instance.",
			},
			"summary": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Brief overview of this alarm instance.",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Full description of this alarm instance.",
			},
			"recommended_action": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Guidance on how to address this alarm instance.",
			},
			"resource_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Identifier of the resource this alarm instance was raised for.",
			},
			"value": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Current reported value associated with the alarm.",
			},
		},
	}
}

func (r *AlarmStateResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, err := GetClientFromProviderData(req.ProviderData)
	if err != nil {
		resp.Diagnostics.AddError("Unexpected provider data type", err.Error())
		return
	}
	r.client = c
}

func (r *AlarmStateResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data AlarmStateResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if err := r.updateState(ctx, &data); err != nil {
		resp.Diagnostics.AddError("Error updating alarm instance state", err.Error())
		return
	}
	if err := r.readInstance(ctx, &data); err != nil {
		resp.Diagnostics.AddError("Error reading alarm instance after updating its state", err.Error())
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AlarmStateResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data AlarmStateResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if err := r.readInstance(ctx, &data); err != nil {
		if err == errAlarmInstanceNotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading alarm instance", err.Error())
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AlarmStateResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data AlarmStateResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if err := r.updateState(ctx, &data); err != nil {
		resp.Diagnostics.AddError("Error updating alarm instance state", err.Error())
		return
	}
	if err := r.readInstance(ctx, &data); err != nil {
		resp.Diagnostics.AddError("Error reading alarm instance after updating its state", err.Error())
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// Delete removes the resource from Terraform state only: there is no API to
// undo an alarm acknowledgement/suppression or delete an alarm instance.
func (r *AlarmStateResource) Delete(_ context.Context, _ resource.DeleteRequest, _ *resource.DeleteResponse) {
}

func (r *AlarmStateResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	var data AlarmStateResourceModel
	data.ID = types.StringValue(req.ID)
	if err := r.readInstance(ctx, &data); err != nil {
		resp.Diagnostics.AddError("Error importing alarm instance", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

var errAlarmInstanceNotFound = fmt.Errorf("alarm instance not found")

func (r *AlarmStateResource) updateState(ctx context.Context, data *AlarmStateResourceModel) error {
	values := url.Values{}
	values.Set("updated_state", data.DesiredState.ValueString())
	if !data.SuppressDuration.IsNull() {
		values.Set("suppress_duration", strconv.FormatInt(data.SuppressDuration.ValueInt64(), 10))
	}

	body := client.UpdateAlarmInstancesRequest{Instances: []string{data.ID.ValueString()}}
	_, err := r.client.Post(ctx, "/ssp/alarms/states?"+values.Encode(), &body, nil)
	if err != nil {
		return fmt.Errorf("POST /ssp/alarms/states: %w", err)
	}
	return nil
}

func (r *AlarmStateResource) readInstance(ctx context.Context, data *AlarmStateResourceModel) error {
	id := data.ID.ValueString()
	var instance client.AlarmInstance
	httpStatus, err := r.client.Get(ctx, "/ssp/alarms/"+id, &instance)
	if httpStatus == 404 {
		return errAlarmInstanceNotFound
	}
	if err != nil {
		return fmt.Errorf("GET /ssp/alarms/%s: %w", id, err)
	}

	data.ID = types.StringValue(id)
	data.State = types.StringValue(instance.State)
	data.FeatureName = types.StringValue(instance.FeatureName)
	data.Severity = types.StringValue(instance.Severity)
	data.Summary = types.StringValue(instance.Summary)
	data.Description = types.StringValue(instance.Description)
	data.RecommendedAction = types.StringValue(instance.RecommendedAction)
	data.ResourceID = types.StringValue(instance.ResourceID)
	data.Value = types.StringValue(instance.Value)
	return nil
}
